spring.application.name=backend
app:
  base-url: https://e-commerce-back-1-yvfs.onrender.com
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            redirect-uri: "${app.base-url}/callback"
